### PR TITLE
Issue 64

### LINKED ISSUE #64: AwsDiscoveryStrategy.discoverNodes throws exception causes node to shutdown immediately
When member try to make the initial connection, `DiscoveryJoiner.getPossibleAddressesForInitialJoin` called, which calls `AwsDiscoveryStrategy.discoverNodes`. If any exception happens, this goes all the way back to `TCPJoiner` & causes node to shut down immediately instead of waiting to join. See below exception. Is this an expected behaviour?

```

2018-04-06 16:08:18,927Z INFO  [main] com.hazelcast.instance.Node - [10.205.89.32]:11415 [dev] [3.9.3] Activating Discovery SPI Joiner

2018-04-06 16:08:19,027Z INFO  [main] com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl - [10.205.89.32]:11415 [dev] [3.9.3] Starting 16 partition threads and 9 generic threads (1 dedicated for priority tasks)

2018-04-06 16:08:19,030Z INFO  [main] com.hazelcast.internal.diagnostics.Diagnostics - [10.205.89.32]:11415 [dev] [3.9.3] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.

2018-04-06 16:08:19,034Z INFO  [main] com.hazelcast.core.LifecycleService - [10.205.89.32]:11415 [dev] [3.9.3] [10.205.89.32]:11415 is STARTING

2018-04-06 16:08:19,056Z INFO  [main] com.hazelcast.system - [10.205.89.32]:11415 [dev] [3.9.3] Cluster version set to 3.9

2018-04-06 16:08:19,064Z INFO  [main] com.hazelcast.spi.hotrestart - [10.205.89.32]:11415 [dev] [3.9.3] hz._hzInstance_1_dev.s00 homeDir: /home/ec2-user/HR_DATA/s00

2018-04-06 16:08:19,086Z INFO  [main] com.hazelcast.spi.hotrestart - [10.205.89.32]:11415 [dev] [3.9.3] hz._hzInstance_1_dev.s01 homeDir: /home/ec2-user/HR_DATA/s01

2018-04-06 16:08:29,213Z ERROR [main] com.hazelcast.internal.cluster.impl.DiscoveryJoiner - [10.205.89.32]:11415 [dev] [3.9.3] java.net.SocketTimeoutException: connect timed out

com.hazelcast.core.HazelcastException: java.net.SocketTimeoutException: connect timed out

      at com.hazelcast.util.ExceptionUtil$1.create(ExceptionUtil.java:40)

      at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:124)

      at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:69)

      at com.hazelcast.util.ExceptionUtil.rethrow(ExceptionUtil.java:129)

      at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:167)

      at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:74)

      at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:70)

      at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:59)

      at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:131)

      at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:90)

      at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:134)

      at com.hazelcast.instance.Node.join(Node.java:690)

      at com.hazelcast.instance.Node.start(Node.java:390)

      at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:133)

      at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:195)

      at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:174)

      at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:124)

      at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:58)

      at com.vertex.c1.hotrestart.HRMain.runServer(HRMain.java:429)

      at com.vertex.c1.hotrestart.HRMain.run(HRMain.java:167)

      at com.vertex.c1.hotrestart.HRMain.main(HRMain.java:146)

Caused by: java.net.SocketTimeoutException: connect timed out

      at java.net.PlainSocketImpl.socketConnect(Native Method)

      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)

      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)

      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

      at java.net.Socket.connect(Socket.java:589)

      at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)

      at sun.net.NetworkClient.doConnect(NetworkClient.java:175)

      at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)

      at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)

      at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)

      at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)

      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)

      at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)

      at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)

      at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)

      at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)

      at com.hazelcast.aws.impl.DescribeInstances.callService(DescribeInstances.java:243)

      at com.hazelcast.aws.impl.DescribeInstances.execute(DescribeInstances.java:227)

      at com.hazelcast.aws.AWSClient.getAddresses(AWSClient.java:56)

      at com.hazelcast.aws.AwsDiscoveryStrategy.discoverNodes(AwsDiscoveryStrategy.java:146)

      ... 16 more

2018-04-06 16:08:29,216Z ERROR [main] com.hazelcast.instance.Node - [10.205.89.32]:11415 [dev] [3.9.3] Could not join cluster in 300000 ms. Shutting down now!
```

### PR DESCRIPTION
**Pull request by leszko**
Add retrying mechanism for AWS endpoint calls.

fix #64 

Changes:
- Add property: "connection-retries" which specifies the number of retries if AWS endpoint connection fails
- Add retrying mechanism for `DescribeInstances` and `MetadataUtil`
- Extract com.hazelcast.aws.AwsConfig from com.hazelcast.config.AwsConfig (before the config for the discovery was stored in hazelcast-root and shared with the deprecated method of nodes discovery)
- Refactor: Move setting default parameters to `AwsDiscoveryStrategy` (before it was partly in `AwsDiscoveryStrategy`, partly in `AwsConfig`)
- Refactor: Move `hzPort` into `AwsConfig`
- Change not to throw an exception but to log it and return an empty collection (prevent node crash when AWS services are overloaded)

### CODE REVIEW

**Comment by leszko** [comment]
Good idea @googlielmo . I'll add it and ping you to have a look!. Thanks :)

**Comment by leszko** [comment]
@googlielmo , I've added the exponential backoff. PTAL.

File: src/main/java/com/hazelcast/aws/utility/RetryUtils.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+
+import java.util.concurrent.Callable;
+
+/**
+ * Static utility class to retry operations related to connecting to AWS Services.
+ */
+public final class RetryUtils {
+    static final long INITIAL_BACKOFF_MS = 1500L;
+    static final long MAX_BACKOFF_MS = 5 * 60 * 1000L;
+    static final double BACKOFF_MULTIPLIER = 1.5;
```
Comment (googlielmo) [inline src/main/java/com/hazelcast/aws/utility/RetryUtils.java]: Pretty reasonable values: Maybe in the future we could make them configurable (nice to have but not needed for this PR!)

File: src/main/java/com/hazelcast/aws/AwsProperties.java [hunk 2]
```diff
@@ -82,6 +81,11 @@
      */
     CONNECTION_TIMEOUT_SECONDS("connection-timeout-seconds", INTEGER, true),
 
+    /**
+     * Number of retries while connecting to AWS Services. Its default value is 10.
```
Comment (mesutcelik) [inline src/main/java/com/hazelcast/aws/AwsProperties.java]: is this Metadata Service? giving more info here could be helpful for other people.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html

File: src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java [hunk 3]
```diff
@@ -17,13 +17,19 @@
...
 import com.hazelcast.util.ExceptionUtil;
 
 import java.util.Collection;
 
+/**
+ * Joiner used for the deprecated AwsConfig.
+ *
+ * @deprecated Use {@link AwsDiscoveryStrategy} instead of AwsConfig.
+ */
+@Deprecated
```
Comment (mesutcelik) [inline src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java]: As long as `<aws>` tag uses TcpIpJoinerOverAWS we can't remove it so I think we need to clean-up hazelcast-core.
https://github.com/hazelcast/hazelcast/blob/fcb2de539ae0a6cbe943daa8322505aa48411ddd/hazelcast/src/main/java/com/hazelcast/instance/Node.java#L758

Comment (leszko) [reply src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java]: Yes, agree. That was actually my meaning of @Deprecated. With the next major hazelcast-aws release, we should remove it both here and in Hazelcast Core.

@mesutcelik Do you think we need to wait for the Hazelcast 4 to clean it up? :) Or the <aws> part does not need to be backward compatible in Hazelcast Core?

File: src/main/java/com/hazelcast/aws/AwsProperties.java (hunk 2 above)
Comment (leszko) [reply src/main/java/com/hazelcast/aws/AwsProperties.java]: Good point. Actually, it's about all AWS services we use (DescribeInstances and InstanceMetadata). Added a comment.

**Comment by leszko** [comment]
@mesutcelik It's kind-of fixing #28. See my comment there. Then, we can decide if it's good enough this way.

Technically, we could retry on empty results, however it's not a good idea, because the meaning of empty result is that there no other nodes discovered. So why to retry it? In any case, I'd move the discussion to #28, because it's not really related to this PR.

File: src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java (hunk 3 above)
Comment (mesutcelik) [reply src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java]: We were normally putting `@deprecated` in between minor releases. It does not have to be between minor releases. On the other hand, we can consider this TcpIpJoinerOverAWS an internal API so `@deprecated` might not even be needed. It is just a matter of timing for `<aws>` tag be using Discovery SPI under the hood... I think @mmedenjak would be happy if you do the cleanup :)

**Comment by mesutcelik** [comment]
empty means to me either tags are not propagated as described in #28 or there is no tag configured although they are defined in hazelcast config.
It is good idea to move the discussion to #28

File: src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java (hunk 3 above)
Comment (leszko) [reply src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java]: The discussion is really about if we want to be backward compatible with the "<aws>" feature. I'd vote for "no", but let's discuss it separately. If we decide to remove it, I'd be happy to do it both HZ Root and hazelcast-aws repos.

Comment (mmedenjak) [reply src/main/java/com/hazelcast/cluster/impl/TcpIpJoinerOverAWS.java]: Hi guys. I can't remember the exact details but I guess the problem was mostly with removing the `aws` tag (and you mention `TcpIpJoinerOverAWS`). As with removing anything in core, it's a problem. We usually wait for 4.0 to remove API as some customers might be using some old API and we guarantee to be backwards compatible. I can't remember if we even ever removed something after marking it as `@Deprecated`.
But if you think it's really necessary, we might consider it.
